version: '3.8'

services:
  delphi-reader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delphi-reader-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - delphi-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  delphi-network:
    driver: bridge
